setopt no_global_rcs
setopt AUTO_CD

: "ディレクトリ履歴" && {
  cdpath=(
#      $HOME/projects(N-/)
#      $HOME/go/src/github.com/suin(N-/)
      $cdpath
  )
}

: "jEnv" && {
  export JENV_ROOT="$HOME/.jenv"
}

: "anyEnv" && {
  export ANYENV_ROOT="$HOME/.anyenv"
}

: "PATH設定" && {
  path=(
    $ANYENV_ROOT/bin(N-/)
    $JENV_ROOT/bin
    /usr/local/opt/gettext/bin
    /usr/local/opt/gpg-agent/bin
    /usr/local/bin
    $path
  )
}

: "GPG" && {
  export GPG_TTY=$(tty)
}
