[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
## Color scheme.
## Add color scheme.
## https://github.com/rafi/awesome-vim-colorschemes
repo = 'dracula/vim'
hook_add = '''
  " colorscheme 設定は source 後に行う必要があるので VimEnter で行う。
  " 但し Colorscheme イベントの発生が抑制されないよう nented を付ける。
  au MyAutoCmd VimEnter * nested colorscheme dracula
'''

[[plugins]]
## lightline vim.
## A light and configurable statusline/tabline plugin for Vim.
## https://github.com/itchyny/lightline.vim.
repo = 'itchyny/lightline.vim'

[[plugins]]
## lightline ale.
## This plugin provides ALE indicator for the lightline vim plugin.
## https://github.com/maximbaz/lightline-ale
repo = 'maximbaz/lightline-ale'

[[plugins]]
## vim-better-whitespace.
## Show white space and remove them.
## https://github.com/ntpeters/vim-better-whitespace
repo = 'ntpeters/vim-better-whitespace'

[[plugins]]
## vim-indent-guides.
## Show indent guide lines.
## https://github.com/nathanaelkane/vim-indent-guides
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
## NERDTree.
## Add file explorer.
## https://github.com/scrooloose/nerdtree
repo = 'scrooloose/nerdtree'
on_cmd = 'NERDTreeToggle'
#@ repo = 'justinmk/vim-dirvish'  " light weight file explorer for big project.

[[plugins]]
## tagbar.
## Show Tag list by tagbar.
## https://github.com/majutsushi/tagbar
repo = 'majutsushi/tagbar'
on_cmd = 'TagbarToggle'

[[plugins]]
## Fazy search by fazy finder.
## https://github.com/junegunn/fzf
# PlugInstall and PlugUpdate will clone fzf in ~/.fzf and run the install script
repo = 'junegunn/fzf'
build = './install --all'
  # Both options are optional. You don't have to install fzf in ~/.fzf
  # and you don't have to run the install script if you use fzf only in Vim.
repo = 'junegunn/fzf.vim'

[[plugins]]
## vim-polyglot.
## A collection of language packs for Vim.
## https://github.com/sheerun/vim-polyglot
repo = 'sheerun/vim-polyglot'

[[plugins]]
## ALE (Asynchronous Lint Engine) is a plugin providing linting (syntax checking and semantic errors) in NeoVim 0.2.0+
## and Vim 8 while you edit your text files, and acts as a Vim Language Server Protocol client.
## https://github.com/dense-analysis/ale
repo = 'dense-analysis/ale'

[[plugins]]
## Ultisnip.
## UltiSnips is the ultimate solution for snippets in Vim. It has many features, speed being one of them.
## https://github.com/SirVer/ultisnips
repo = 'SirVer/ultisnips'

[[plugins]]
## snipMate & UltiSnip Snippets.
## Use in combination with 'ultisnips'.
## https://github.com/honza/vim-snippets
repo = 'honza/vim-snippets'

[[plugins]]
## Conquer of Completion
## Coc is an intellisense engine for Vim/Neovim.
## https://github.com/neoclide/coc.nvim
repo = 'neoclide/coc.nvim'
rev = 'release'

[[plugins]]
## Terminal emulator.
## Use the same terminal for everything.
## https://github.com/kassio/neoterm
repo = 'kassio/neoterm'

[[plugins]]
## Vim Commentary.
## Comment in/out utility.
## https://github.com/tpope/vim-commentary
repo = 'tpope/vim-commentary'

[[plugins]]
## Unudo tree
## Visualizes undo history and makes it easier to browse and switch between different undo branches.
## https://github.com/mbbill/undotree
repo = 'mbbill/undotree'

[[plugins]]
## Vim-easymotion.
## EasyMotion provides a much simpler way to use some motions in vim.
## https://github.com/easymotion/vim-easymotion
repo = 'easymotion/vim-easymotion'

[[plugins]]
## Sorround vim.
## Surround.vim is all about "surroundings": parentheses, brackets, quotes, XML tags, and more.
## https://github.com/tpope/vim-surround
repo = 'tpope/vim-surround'

[[plugins]]
## vim-repeat.
## Repeat plugin map.
## https://github.com/tpope/vim-repeat
repo = 'tpope/vim-repeat'

[[plugins]]
## Auto Pairs
## Insert or delete brackets, parens, quotes in pair.
## https://github.com/jiangmiao/auto-pairs
repo = 'jiangmiao/auto-pairs'

[[plugins]]
## fugitive vim.
## fugitive.vim may very well be the best Git wrapper of all time.
## https://github.com/tpope/vim-fugitive
repo = 'tpope/vim-fugitive'

[[plugins]]
 ## vim-gitgutter
## A Vim plugin which shows a git diff in the 'gutter' (sign column).
## https://github.com/airblade/vim-gitgutter
repo = 'airblade/vim-gitgutter'

[[plugins]]
## Rooter
## Rooter changes the working directory to the project root when you open a file or directory.
## https://github.com/airblade/vim-rooter
repo = 'airblade/vim-rooter'

[[plugins]]
## vim match-up
## match-up is a drop-in replacement for the vim plugin matchit.vim.
## https://github.com/andymass/vim-matchup
repo = 'andymass/vim-matchup'

[[plugins]]
## Emmet-vim
## emmet-vim is a vim plug-in which provides support for expanding abbreviations similar to emmet.
## https://github.com/mattn/emmet-vim
repo = 'mattn/emmet-vim'

[[plugins]]
## vim-expand-region
## vim-expand-region is a Vim plugin that allows you to visually select increasingly larger regions of text using the same key combination.
## https://github.com/terryma/vim-expand-region
repo = 'terryma/vim-expand-region'

